# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Backend and deploy to SECURITY

on:
  push:
    branches:
      - stage-on-security
    paths:
      - backend/**
      - .github/workflows/backend*.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Deploy Backend
      if: success()
      uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: ${{ secrets.CF_API }}
        cf_org: ${{ secrets.CF_ORG }}
        cf_space: ${{ secrets.CF_SPACE }}
        cf_username: ${{ secrets.CF_USERNAME }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        command: push quarano-backend-sec-f ../m
